### PR TITLE
WIP Add nullable

### PR DESCRIPTION
**Pull request by stephane-alnet**
The purpose of this PR is to add support for nullable.

However, while trying to add `nullable` (using the hints from #37 ) I had to upgrade ajv (to insert a version that supports nullable) which led to upgrading @types/json-schema then typescript etc. This lead to some corrections (essentially, `B.True` no longer exists).

However, even if upgrade to the latest versions of the toolset (as is done here), I'm still getting the following two errors, which seem to be unrelated to the addition of nullable (but I might be mistaken):
```
tests/meta-types/intersection/enum.ts:157:7 - error TS2322: Type '1' is not assignable to type '0'.

157 const nonIntersectingUnion: A.Equals<
          ~~~~~~~~~~~~~~~~~~~~

tests/meta-types/intersection/union.ts:145:7 - error TS2322: Type '1' is not assignable to type '0'.

145 const nonIntersectingUnion: A.Equals<
          ~~~~~~~~~~~~~~~~~~~~


Found 2 errors.
```

I would appreciate your input @ThomasAribart on the errors, and eventually on the PR itself.

### CODE REVIEW

**Comment by stephane-alnet** [comment]
Actually updating the dependencies (and ignoring the compilation-time errors for now) also adds 95 warnings and 5 errors from `ajv`. I'm only listing the errors here:
```
● If/Then/Else schemas › additional items (incorrect) › rejects invalid dog instances
  strict mode: "additionalItems" is ignored when "items" is not an array of schemas
● Not schemas › additionalItems › accepts correct item
  strict mode: "additionalItems" is ignored when "items" is not an array of schemas
● AllOf schemas › Factored tuple properties › Incorrect schema › accepts tuples with any additional items
  strict mode: "additionalItems" is ignored when "items" is not an array of schemas
● AnyOf schemas › Factored tuple properties › Incorrect schema › accepts tuples with any additional items
  strict mode: "additionalItems" is ignored when "items" is not an array of schemas
● OneOf schemas › Factored tuple properties › Incorrect schema › accepts tuples with any additional items
  strict mode: "additionalItems" is ignored when "items" is not an array of schemas
```

This is all unrelated to adding `nullable`, and — honestly — way over my head since these are Schema features I have never used. :|

**Comment by stephane-alnet** [comment]
Documenting the upgrade path:
- original code fails due to ajv expecting `string` (nullable not supported);
- ajv 8.8.2 → TS compile-time error in `json-schema`:
  ```
  declare type StrictNullChecksWrapper<Name extends string, Type> = undefined extends null ? `strictNullChecks must be true in tsconfig to use ${Name}` : Type;`
  ```
  (since `strictNullChecks` is already `true` in package.json I assume this is due to TS bug)
- upgrading to TS 4.5.4 corrects the compile-time error in `@types/json-schema` but fails at compile-time for the cotests indicated in the original post.

**Comment by ThomasAribart** [comment]
Hello @stephane-alnet and thanks for the PR and your inputs ! I'll take a look at it ASAP :)

**Comment by stephane-alnet** [comment]
Corrected `nullable` support.

**Comment by ThomasAribart** [comment]
Available in v2.1.2, closed by https://github.com/ThomasAribart/json-schema-to-ts/pull/62

**Pull request closed without merging**
